package edu.slu.cs.implementation;

import java.util.*;
import java.util.stream.Collectors;
import edu.slu.cs.model.*;

public class BankServices {
    private final List<Customer> customers = new ArrayList<>();

    // --- Customer Management ---

    public Customer addCustomer(String firstName,
                                String lastName,
                                String birthDate,
                                String phoneNumber) {
        if (getCustomerByPhone(phoneNumber) != null) {
            throw new IllegalArgumentException("Customer with this phone number already exists");
        }
        Customer customer = new Customer(firstName, lastName, birthDate, phoneNumber);
        customers.add(customer);
        return customer;
    }

    public Customer getCustomerByPhone(String phoneNumber) {
        return customers.stream()
                .filter(c -> c.getPhoneNumber().equals(phoneNumber))
                .findFirst()
                .orElse(null);
    }

    public List<Customer> getAllCustomers() {
        return Collections.unmodifiableList(customers);
    }

    public void removeCustomer(String phoneNumber) {
        boolean removed = customers.removeIf(c -> c.getPhoneNumber().equals(phoneNumber));
        if (!removed) throw new NoSuchElementException("Customer not found");
    }

    // --- Customer Sign-In/Account Usage ---

    public Customer signIn(int accountNo) {
        return customers.stream()
                .filter(c -> c.getAccounts().stream()
                        .anyMatch(a -> a.getAccountNo() == accountNo))
                .findFirst()
                .orElse(null);
    }

    // --- Account Operations per Customer ---

    /**
     * Creates a new bank account under the given customer.
     * Account number is auto-generated by BankAccount.
     */
    public BankAccount createAccountForCustomer(Customer customer, String type) {
        BankAccount newAcc;

        do {
            newAcc = switch (type) {
                case "Savings" -> new BankAccount(customer.getFirstName(), customer.getLastName());
                case "Checking" -> new CheckingAccount(customer.getFirstName(), customer.getLastName(), 500.0);
                case "Credit" -> new CreditCardAccount(customer.getFirstName(), customer.getLastName(), 25000);
                case "Investment" -> new InvestmentAccount(customer.getFirstName(), customer.getLastName(), 5000, 0.35);
                default -> throw new IllegalArgumentException("Unknown account type");
            };
        } while (searchAccountByNumber(newAcc.getAccountNo()) != null);
        customer.addAccount(newAcc);
        return newAcc;
    }

    public void deposit(Customer customer, int accountNo, double amount) {
        getAccountOrThrow(customer, accountNo).deposit(amount);
    }

    public void withdraw(Customer customer, int accountNo, double amount) {
        getAccountOrThrow(customer, accountNo).withdraw(amount);
    }

    public void transfer(Customer customer,
                         int fromAccNo,
                         int toAccNo,
                         double amount) {
        BankAccount from = getAccountOrThrow(customer, fromAccNo);
        BankAccount to = customers.stream()
                .flatMap(c -> c.getAccounts().stream())
                .filter(a -> a.getAccountNo() == toAccNo)
                .findFirst()
                .orElseThrow(() -> new NoSuchElementException("Target account not found"));
        from.transferMoney(toAccNo, amount,
                (ArrayList<BankAccount>) customers.stream()
                        .flatMap(c -> c.getAccounts().stream())
                        .collect(Collectors.toList()));
    }

    public void closeAccount(Customer customer, int accountNo) {
        customer.removeAccount(accountNo);
    }

    public double inquireBalance(Customer customer, int accountNo) {
        return getAccountOrThrow(customer, accountNo).inquireBalance();
    }

    public String getAccountInfo(Customer customer, int accountNo) {
        return getAccountOrThrow(customer, accountNo).toString();
    }

    // --- Search Accounts ---

    public List<BankAccount> searchAccountsByName(String nameKeyword) {
        String key = nameKeyword.toLowerCase();
        return customers.stream()
                .flatMap(c -> c.getAccounts().stream())
                .filter(a -> a.getFirstName().toLowerCase().contains(key)
                        || a.getLastName().toLowerCase().contains(key))
                .collect(Collectors.toList());
    }

    public BankAccount searchAccountByNumber(int accountNo) {
        return customers.stream()
                .flatMap(c -> c.getAccounts().stream())
                .filter(a -> a.getAccountNo() == accountNo)
                .findFirst()
                .orElse(null);
    }

    // --- Edit Account Details ---

    public void editAccountName(Customer customer, int accountNo, String newFirstName, String newLastName) {
        BankAccount acc = getAccountOrThrow(customer, accountNo);
        acc.setFirstName(newFirstName);
        acc.setLastName(newLastName);
    }

    // --- Edit Transactions ---

    public void editTransaction(Customer customer,
                                int accountNo,
                                int transactionId,
                                double newAmount) {
        BankAccount acc = getAccountOrThrow(customer, accountNo);
        // TODO: implement transaction editing
    }

    // --- Credit Card Specific ---

    public double inquireAvailableCredit(Customer customer, int accountNo) {
        BankAccount acc = getAccountOrThrow(customer, accountNo);
        if (acc instanceof CreditCardAccount) {
            CreditCardAccount cc = (CreditCardAccount) acc;
            cc.inquireAvailableCredit();
        }
        throw new IllegalArgumentException("Not a credit card account");
    }

    public void cashAdvance(Customer customer, int accountNo, double amount) {
        BankAccount acc = getAccountOrThrow(customer, accountNo);
        if (acc instanceof CreditCardAccount) {
            CreditCardAccount cc = (CreditCardAccount) acc;
            cc.getCashAdvance(amount);
        }
        else throw new IllegalArgumentException("Not a credit card account");
    }

    // TODO: payCard, chargeToCard

    // --- Investment Specific ---

    public void addInvestment(Customer customer, int accountNo, double amount) {
        BankAccount acc = getAccountOrThrow(customer, accountNo);
        if (acc instanceof InvestmentAccount) {
            InvestmentAccount ia = (InvestmentAccount) acc;
            ia.addInvestment(amount);
        }
        else throw new IllegalArgumentException("Not an investment account");
    }

    public double inquireInvestmentValue(Customer customer, int accountNo) {
        BankAccount acc = getAccountOrThrow(customer, accountNo);
        if (acc instanceof InvestmentAccount) {
            InvestmentAccount ia = (InvestmentAccount) acc;
            ia.inquireInvestmentValue();
        }
        throw new IllegalArgumentException("Not an investment account");
    }

    // --- Helpers ---

    private BankAccount getAccountOrThrow(Customer customer, int accountNo) {
        BankAccount acc = customer.getAccount(accountNo);
        if (acc == null) throw new NoSuchElementException("Account not found for this customer");
        return acc;
    }

    // TODO: Add more necessary methods if needed, will test when GUI is ready
}

